# Generated by Django 4.1.6 on 2023-02-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='repo_url',
            field=models.URLField(default='ex'),
            preserve_default=False,
        ),
    ]
