# Generated by Django 4.1.6 on 2023-02-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_education_experience_alter_repo_repo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='url',
            field=models.URLField(blank=True, help_text='address url', null=True),
        ),
    ]
