# Generated by Django 4.1.6 on 2023-02-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='1', upload_to='teams'),
            preserve_default=False,
        ),
    ]
